import { BaseProps } from '@wavemaker/app-rn-runtime/core/base.component';

export default class BaseChartComponentProps extends BaseProps {
  xaxisdatakey: string = '';
  yaxisdatakey: string = '';
  iconclass = '';
  dataset: any;
  type: string = '';
  title: string = '';
  subheading: string = '';
  theme: string = '';
  xaxislabel: string = '';
  xunits: string = '';
  staggerlabels: boolean = false;
  yaxislabel: string = '';
  yunits: string = '';
  yaxislabeldistance: number = 60;
  xaxislabeldistance: number = 30;
  customcolors: string | Array<string> = '';
  legendheight: number = 0;
  labellegendheight: number = 0;
  labeltype: 'percent' | 'value' | 'key-value' | 'key' = 'percent';
  bubblesize: string= '';
  shape: string = '';
  loadingicon='fa fa-circle-o-notch fa-pulse';
  loadingdatamsg = 'Loading...';
  nodatamessage = 'No data found';
  offsetbottom: number = 50;
  offsettop: number = 70;
  offsetleft: number = 65;
  offsetright: number = 25;
  showlegend: string = 'top';
  showlabels: 'inside' | 'outside' | 'hide' = 'outside';
  tooltips: boolean = false;
  interpolation: string = 'linear';
  highlightpoints: boolean = false;
  showvalues: boolean = false;
  showyaxis: boolean = true;
  showxaxis: boolean = true;
  ydomain: string = 'Min';
  xdomain: string = 'Min';
  labelangle: number = 0;
  xtickexpr?: (item: any, index: number, length: number) => any;
  ytickexpr?: (item: any, index: number, length: number) => any;
  hidegridxaxis: boolean = false;
  hidegridyaxis: boolean = false;
  autoadjustlabels: boolean = false;
}
